---
title: "basic tests ridge"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

For comparison here is a simple EM algorithm
```{r}
ridge_em1 = function(y,X, s2,sb2, niter=10){
  XtX = t(X) %*% X
  Xty = t(X) %*% y
  yty = t(y) %*% y
  n = length(y)
  p = ncol(X)
  loglik = rep(0,niter)
  for(i in 1:niter){
    V = chol2inv(chol(XtX+ diag(s2/sb2,p))) 
    
    SigmaY = sb2 *(X %*% t(X)) + diag(s2,n)
    loglik[i] = mvtnorm::dmvnorm(as.vector(y),sigma = SigmaY,log=TRUE)
    
    Sigma1 = s2*V  # posterior variance of b
    mu1 = as.vector(V %*% Xty) # posterior mean of b
    
    s2 = as.vector((yty + sum(diag(XtX %*% (mu1 %*% t(mu1) + Sigma1)))- 2*sum(Xty*mu1))/n)
    sb2 = mean(mu1^2+diag(Sigma1))
   
  }
  return(list(s2=s2,sb2=sb2,loglik=loglik,postmean=mu1))
}
```


Simulate some data
```{r}
library(ebmr.alpha)
set.seed(100)
sd = 10
n = 200
p = 100
X = matrix(rnorm(n*p),ncol=p)
btrue = rnorm(p)
y = X %*% btrue + sd*rnorm(n)

plot(X %*% btrue, y)

```


```{r}
fit = ebmr(X,y,100)
fit.em = ridge_em1(y,X,1,1,100)
fit$residual_variance
fit.em$s2
fit.em$sb2/fit.em$s2
fit$g


plot(fitted.values(fit),X %*% fit.em$postmean)
```

